// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXKCrPuS1f0UFn9c71yLjqi8GEBn0zOPQ',
    appId: '1:319167576707:android:34d8344551f25f816079b6',
    messagingSenderId: '319167576707',
    projectId: 'flutter-movies-list',
    storageBucket: 'flutter-movies-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAe5h4e6tCXR9ZDJ-qrdl6BD7BhnDB3hE',
    appId: '1:319167576707:ios:ffe9eec1acfd8aca6079b6',
    messagingSenderId: '319167576707',
    projectId: 'flutter-movies-list',
    storageBucket: 'flutter-movies-list.appspot.com',
    androidClientId: '319167576707-8a6rdhlc8kro6hoc9ueovgidkv7t4im8.apps.googleusercontent.com',
    iosClientId: '319167576707-qlqbb2hd4toe0uni944pkqbsuck2uf94.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
